import { StyleSheet } from 'react-native';

export const colors = {
  navy950: '#F8FAFC',
  abyss: '#EFF6FF',
  navy900: '#FFFFFF',
  navy800: '#FFFFFF',
  navy700: '#E0F2FE',
  navy600: '#CBD5E1',
  sidebarNavy: '#FFFFFF',
  accent: '#0077C8',
  accentHover: '#005FA3',
  accentSoft: 'rgba(0, 119, 200, 0.08)',
  cyan: '#0077C8',
  coral: '#DC2626',
  success: '#059669',
  successSoft: 'rgba(5, 150, 105, 0.08)',
  warning: '#D97706',
  warningSoft: 'rgba(217, 119, 6, 0.08)',
  danger: '#DC2626',
  dangerSoft: 'rgba(220, 38, 38, 0.08)',
  textPrimary: '#0F172A',
  textSecondary: '#475569',
  textMuted: '#94A3B8',
  border: '#E2E8F0',
  borderHover: '#CBD5E1',
};

export const shared = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.navy950,
  },
  safeArea: {
    flex: 1,
    backgroundColor: colors.navy950,
  },
  pagePadding: {
    paddingHorizontal: 20,
    paddingVertical: 18,
  },
  card: {
    backgroundColor: colors.navy900,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 20,
    marginBottom: 14,
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.06,
    shadowRadius: 14,
    elevation: 2,
  },
  sectionTitle: {
    color: colors.textMuted,
    fontSize: 11,
    fontWeight: '800',
    marginBottom: 12,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  input: {
    backgroundColor: colors.navy900,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    color: colors.textPrimary,
    fontSize: 15,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  label: {
    fontSize: 11,
    fontWeight: '700',
    color: colors.textMuted,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 6,
  },
  btnPrimary: {
    backgroundColor: colors.accent,
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    flexDirection: 'row' as const,
    gap: 8,
  },
  btnPrimaryText: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '700',
  },
  btnSecondary: {
    backgroundColor: colors.navy700,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    paddingVertical: 12,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
  },
  btnSecondaryText: {
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: '600',
  },
  title: {
    fontSize: 24,
    fontWeight: '800',
    color: colors.textPrimary,
    letterSpacing: 0,
  },
  subtitle: {
    fontSize: 13,
    color: colors.textMuted,
    marginTop: 2,
  },
  headerBar: {
    paddingHorizontal: 20,
    paddingVertical: 18,
    backgroundColor: colors.navy900,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    justifyContent: 'space-between' as const,
  },
  glassCard: {
    backgroundColor: colors.navy900,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 18,
  },
  badge: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
    alignSelf: 'flex-start' as const,
  },
  badgeText: {
    fontSize: 11,
    fontWeight: '700',
  },
});
