import { StyleSheet } from 'react-native';

export const colors = {
  navy950: '#07111F',
  navy900: '#0B1728',
  navy800: '#10213A',
  navy700: '#16304F',
  navy600: '#24476F',
  sidebarNavy: '#091321',
  accent: '#1D9BF0',
  accentHover: '#0E7FCB',
  accentSoft: 'rgba(29, 155, 240, 0.14)',
  cyan: '#53D3F7',
  success: '#36C98E',
  successSoft: 'rgba(54, 201, 142, 0.14)',
  warning: '#FFB84D',
  warningSoft: 'rgba(255, 184, 77, 0.14)',
  danger: '#FF7A7A',
  dangerSoft: 'rgba(255, 122, 122, 0.14)',
  textPrimary: '#F8FBFF',
  textSecondary: '#C9D6E6',
  textMuted: '#8EA4C0',
  border: 'rgba(142, 164, 192, 0.18)',
  borderHover: 'rgba(142, 164, 192, 0.3)',
};

export const shared = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.navy950,
  },
  safeArea: {
    flex: 1,
    backgroundColor: colors.navy950,
  },
  pagePadding: {
    paddingHorizontal: 20,
    paddingVertical: 18,
  },
  card: {
    backgroundColor: colors.navy800,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 20,
    marginBottom: 14,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.16,
    shadowRadius: 24,
    elevation: 8,
  },
  sectionTitle: {
    color: colors.textMuted,
    fontSize: 11,
    fontWeight: '800',
    marginBottom: 12,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  input: {
    backgroundColor: colors.navy900,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    color: colors.textPrimary,
    fontSize: 15,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  label: {
    fontSize: 11,
    fontWeight: '700',
    color: colors.textMuted,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 6,
  },
  btnPrimary: {
    backgroundColor: colors.accent,
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    flexDirection: 'row' as const,
    gap: 8,
  },
  btnPrimaryText: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '700',
  },
  btnSecondary: {
    backgroundColor: colors.navy700,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
  },
  btnSecondaryText: {
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: '600',
  },
  title: {
    fontSize: 24,
    fontWeight: '800',
    color: colors.textPrimary,
    letterSpacing: -0.5,
  },
  subtitle: {
    fontSize: 13,
    color: colors.textMuted,
    marginTop: 2,
  },
  headerBar: {
    paddingHorizontal: 20,
    paddingVertical: 18,
    backgroundColor: colors.navy900,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    justifyContent: 'space-between' as const,
  },
  glassCard: {
    backgroundColor: 'rgba(11, 23, 40, 0.82)',
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 18,
  },
  badge: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
    alignSelf: 'flex-start' as const,
  },
  badgeText: {
    fontSize: 11,
    fontWeight: '700',
  },
});
